### ISSUE TITLE
Dense xUnit Networks

### ISSUE THREAD

**Issue by kayuksel** [kligvasser/xUnit#2]
Dear Idan, I have already implemented some parts of it by also benefiting from this repository but I would also welcome if you can share codes for Dense xUnit Networks so that I can double-check. There is also a similarity of your module with some versions of the Gather-Excite module, I guess.

**Comment by kligvasser** [comment]
Hi Kayuksel,
Thank you for getting interested in our work.
I am about to upload an official code, when we would have a final decision regarding our submission.  
Email me to kligvasser@gmail.com, and I will send you a link to my dropbox. 
Yes, I am familiar with the similarity to GE module, and we are about to discuss it in the final version. Both of the works reweight element within each channel by a scalar that depends on the spatial neighborhood of this element in the previous layer. We reweight a bit differently and consider cross feature map dependencies.

**Comment by oneTaken** [comment]
@kligvasser Nice work. I read your version2 paper and have a question about your explanation of "t**he impact of cross-channel dependencies in xUnits**" in Figure 4.

Whether the performance promotion is caused by more parameter or the cross-channel interaction?
I do not see some details about this discussion in your paper.

Is this possible?

**Comment by kligvasser** [comment]
Hi @oneTaken,
Our modified xUnit provides a performance boost beyond that attained with the original xUnit. We indeed reported results only for denoising, but this behavior is consistent across all tasks. For example, a comparison for CIFAR-10 classification is shown in the table below. In our final version, we will add a relevant discussion. 

![image](https://user-images.githubusercontent.com/16685763/55285506-3459a200-5396-11e9-9901-ba07513d979e.png)

**Comment by kligvasser** [comment]
Closed.
