### ISSUE TITLE
Replacing ReLU in xUnit with Mish

### ISSUE THREAD

**Issue by digantamisra98** [kligvasser/xUnit#3]
Was wondering if there will be an increment in the results posted in the paper of xUnit by simply replacing ReLU with Mish. 
Mish - https://github.com/digantamisra98/Mish

**Comment by kligvasser** [comment]
Hi @digantamisra98,
Thank you for this comment.
In our journal version of this paper, we investigated several xUnit designs:

![image](https://user-images.githubusercontent.com/16685763/69226283-9024a580-0b88-11ea-84c3-2e99c656e252.png)

Some include ReLU and some not. Interestingly, the spatial processing (Depthwise convolution) is what contributes the most. My intuition is with you, replacing the ReLU there with more powerful activation function like Mish, might even further increase performance.

**Comment by digantamisra98** [comment]
@kligvasser Ah I see. Do you want to experiment with some Non-Monotonic Non-linearities like Swish and Mish in place of ReLU? Would be interesting to see the results though I agree the Depthwise Conv contributes the most towards the performance.

**Comment by DonaldTsang** [comment]
@kligvasser A re-investigation is in order as Mish and others are newer than xUnit, and are thus presumably better at dealing with the same task when compared to xUnit.
