### ISSUE TITLE
Waiting for the update of training method

### ISSUE THREAD

**Issue by Yangzhoufly** [kligvasser/xUnit#5]
hello，I'm a junior student .
I am learning  image denoising recently. It is very lucky to find this project, it helps me a lot.
I am wondering whether this project will update the training method，hahaha.

**Comment by Yangzhoufly** [comment]
May i get the trained color-image xUnit model, thank you

**Comment by kligvasser** [comment]
Hi,

Yes, why not... 
I will upload next week code for denoising and super resolution training. Please stay tuned.

**Comment by kligvasser** [comment]
training code is up.
